import { Question } from "./questionModel.js"

export const sport = [
    new Question('Jakie jest największe państwo na świecie pod względem powierzchni?',
        ['Rosja', 'Kanada', 'Stany Zjednoczone', 'Chiny'], 'Rosja'),
    new Question('Które miasto jest stolicą Włoch?',
        ['Rzym', 'Wenecja', 'Florencja', 'Neapol'], 'Rzym'),
    new Question('W którym kraju narodziło się piłka nożna?', ['Niemcy', 'Włochy', 'Anglia', 'Brazylia'], 'Anglia'),
    new Question('Które zespoły grają corocznie w meczu Super Bowl?',
        ['Zwycięzca AFC i NFC', 'Dallas Cowboys i New York Giants', 'Green Bay Packers i Chicago Bears', 'Los Angeles Rams'], 'Zwycięzca AFC i NFC'),
    new Question('W którym kraju odbyły się ostatnie Letnie Igrzyska Olimpijskie?',
        ['Chiny', 'Brazylia', 'Japonia', 'Australia'], 'Japonia'),
    new Question('Co oznacza skrót MMA?',
        ['Mjesto Młodzieżowego Atak', 'Mistrzostwa Mocarstw Afroazjatyckich', 'Najlepszy Miał-Ananasy', 'mieszane sztuki walki'], 'mieszane sztuki walki'),
    new Question('Ile piłkarzy jest na boisku podczas jednej drużyny w czasie meczu piłki nożnej?',
        ['8', '9', '10', '11'], '11'),
    new Question('Z jakiego kraju pochodzi tenisistka Serena Williams?',
        ['USA', 'Kanada', 'Wielka Brytania', 'Francja'], 'USA'),
    new Question('Jak długi jest standardowy półmaraton?',
        ['10 km', '15 km', '21,1 km', '30 km'], '21,1 km'),
    new Question('Gdzie odbyła się pierwsza edycja Festiwalu Piosenki Eurowizji?',
        ['Niemcy', 'Szwajcaria', 'Włochy', 'Francja'], 'Szwajcaria'),
    new Question('Turniej Czterech Skoczni - jaka to dyscyplina?',
        ['Zawody lekkoatletyczne', 'Impreza wspinaczkowa', 'Konkurs skoków narciarskich', 'Regularny sezon gier PC'], 'Konkurs skoków narciarskich'),
]

export const business = [
    new Question('Co oznacza skrót KPI w biznesie?',
        ['Key Performance Indicator', 'Keep People Informed', 'Know-How of Product Information', 'Kindly Provide Insight'], 'Key Performance Indicator'),
    new Question('W którym roku została założona firma Apple?',
        ['1976', '1984', '1995', '2003'], '1976'),
    new Question('Co oznacza skrót ROI w biznesie?',
        ['Return On Investment', 'Rate Of Interest', 'Revenue Of Income', 'Readiness Of Investment'], 'Return On Investment'),
    new Question('Która firma jest największym sprzedawcą książek na świecie?',
        ['Amazon', 'Alibaba', 'Walmart', 'Tesco'], 'Amazon'),
    new Question('Jak nazywa się proces planowania, wdrażania i kontroli operacji marketingowych?',
        ['Strategia marketingowa', 'Marketing szeptany', 'Reklama', 'Kampania marketingowa'], 'Kampania marketingowa'),
    new Question('Co oznacza skrót USP w biznesie?',
        ['Unique Selling Point', 'Universal Sales Platform', 'Ultimate Sales Pitch', 'Unique Service Profit'], 'Unique Selling Point'),
    new Question('Która firma zajmuje się produkcją samochodów elektrycznych?',
        ['Tesla', 'Ford', 'BMW', 'Toyota'], 'Tesla'),
    new Question('Jak nazywa się model biznesowy polegający na wynajmowaniu produktów zamiast ich kupowania?',
        ['Sharing economy', 'Traditional economy', 'Consumption economy', 'Ownership economy'], 'Sharing economy'),
    new Question('aka jest nazwa podręcznego urządzenia przenośnego, które umożliwia bezprzewodowe połączenie z Internetem?',
        ['Router', 'Modem', 'Switch', 'Access point'], 'Router'),
    new Question('Co oznacza skrót CRM w biznesie?',
        ['Customer Relationship Management', 'Commercial Retail Market', 'Creative Resource Management', 'Business Development Software'], 'Customer Relationship Management'),
]